# ip 限制
filter:
  minute: 1
  times: 100

# datasource
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://localhost:3306/lg_work?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  username: "root"
  password: "021998"

# 邮件
mail:
  # 用户名
  username: pasta0101@qq.com
  # 授权码
  password: yyxpuazkvcxobdhh
  # 邮箱供应的 SMTP 地址
  host: smtp.qq.com
